source 'https://github.com/CocoaPods/Specs.git'



platform :ios, '8.0'

target 'YYBundle_Example' do
  pod 'YYBundle', :path => '../'

  target 'YYBundle_Tests' do
    inherit! :search_paths

    
  end
end
